/*
 * rcc.c
 *
 *  Created on: Apr 4, 2025
 *      Author: lucas
 */

#include "stm32f4xx_hal.h"
#include"rcc.h"

void configureRCC_APB1(void)
{
	RCC->APB1ENR &= ~(RCC_APB1ENR_I2C2EN | RCC_APB1ENR_TIM4EN |RCC_APB1ENR_USART3EN);
	RCC->APB1ENR |= (RCC_APB1ENR_I2C2EN | RCC_APB1ENR_TIM4EN |RCC_APB1ENR_USART3EN);
	__ASM("NOP");
	__ASM("NOP");
	RCC->APB1RSTR &= ~(RCC_APB1RSTR_I2C2RST | RCC_APB1RSTR_TIM4RST |RCC_APB1RSTR_USART3RST);

}



void configureRCC_APB2(void)
{
	RCC->APB2ENR &= ~(RCC_APB2ENR_SPI1EN | RCC_APB2ENR_SYSCFGEN | RCC_APB2ENR_SPI6EN | RCC_APB2ENR_TIM1EN);
	RCC->APB2ENR |= (RCC_APB2ENR_SPI1EN | RCC_APB2ENR_SYSCFGEN | RCC_APB2ENR_SPI6EN | RCC_APB2ENR_TIM1EN);
	__ASM("NOP");
	__ASM("NOP");
	RCC->APB1RSTR &= ~(RCC_APB2RSTR_SPI1RST | RCC_APB2RSTR_SYSCFGRST | RCC_APB2RSTR_SPI6RST | RCC_APB2RSTR_TIM1RST);
}

void configureRCC_AHB1(void)
{
	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN
			| RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOEEN | RCC_AHB1ENR_GPIOFEN
			| RCC_AHB1ENR_GPIOGEN | RCC_AHB1ENR_GPIOHEN | RCC_AHB1ENR_GPIOIEN
			| RCC_AHB1ENR_GPIOJEN | RCC_AHB1ENR_GPIOKEN | RCC_AHB1ENR_DMA1EN
			| RCC_AHB1ENR_DMA2EN);
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN
			| RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOEEN | RCC_AHB1ENR_GPIOFEN
			| RCC_AHB1ENR_GPIOGEN | RCC_AHB1ENR_GPIOHEN | RCC_AHB1ENR_GPIOIEN
			| RCC_AHB1ENR_GPIOJEN | RCC_AHB1ENR_GPIOKEN | RCC_AHB1ENR_DMA1EN
			| RCC_AHB1ENR_DMA2EN);
	__ASM("NOP");
	__ASM("NOP");
	RCC->AHB1RSTR &= (uint16_t)(~(RCC_AHB1RSTR_GPIOARST | RCC_AHB1RSTR_GPIOBRST | RCC_AHB1RSTR_GPIOCRST
			| RCC_AHB1RSTR_GPIODRST | RCC_AHB1RSTR_GPIOERST | RCC_AHB1RSTR_GPIOFRST
			| RCC_AHB1RSTR_GPIOGRST | RCC_AHB1RSTR_GPIOHRST | RCC_AHB1RSTR_GPIOIRST
			| RCC_AHB1RSTR_GPIOJRST | RCC_AHB1RSTR_GPIOKRST | RCC_AHB1ENR_DMA1EN
			| RCC_AHB1ENR_DMA2EN)); //resets the peripheral!

}
